// FORGE — Seed data for courses, books, prompts, and templates
// Used to populate the database on first deploy

export const SEED_COURSES = [
  {
    slug: 'ai-fundamentals',
    title: 'AI Fundamentals',
    titleNoDiacritics: 'AI Fundamentals',
    description: 'Learn the basics of AI, machine learning, and how to use AI tools effectively.',
    descriptionNoDiacritics: 'Learn the basics of AI, machine learning, and how to use AI tools effectively.',
    icon: 'Brain',
    color: '#3b82f6',
    level: 'beginner',
    tags: ['ai', 'basics', 'ml'],
    totalLessons: 12,
    estimatedHours: 6,
    isPublished: true,
    modules: [
      {
        title: 'Introduction to AI',
        order: 0,
        lessons: [
          { slug: 'what-is-ai', title: 'What is AI?', type: 'explanation', estimatedMinutes: 15, order: 0 },
          { slug: 'ai-vs-ml', title: 'AI vs ML vs Deep Learning', type: 'explanation', estimatedMinutes: 20, order: 1 },
          { slug: 'ai-use-cases', title: 'Real-World AI Use Cases', type: 'explanation', estimatedMinutes: 25, order: 2 },
        ],
      },
      {
        title: 'Working with AI Tools',
        order: 1,
        lessons: [
          { slug: 'prompt-engineering', title: 'Prompt Engineering Basics', type: 'explanation', estimatedMinutes: 30, order: 0 },
          { slug: 'chatgpt-claude', title: 'ChatGPT, Claude, and Gemini', type: 'explanation', estimatedMinutes: 25, order: 1 },
          { slug: 'ai-coding-tools', title: 'AI Coding Tools (Cursor, Copilot)', type: 'explanation', estimatedMinutes: 30, order: 2 },
        ],
      },
    ],
  },
  {
    slug: 'web-development',
    title: 'Web Development Zero to Hero',
    titleNoDiacritics: 'Web Development Zero to Hero',
    description: 'Build modern web apps with HTML, CSS, JavaScript, and React. No experience needed.',
    descriptionNoDiacritics: 'Build modern web apps with HTML, CSS, JavaScript, and React. No experience needed.',
    icon: 'Code2',
    color: '#f59e0b',
    level: 'beginner',
    tags: ['web', 'html', 'css', 'javascript', 'react'],
    totalLessons: 20,
    estimatedHours: 15,
    isPublished: true,
    modules: [
      {
        title: 'HTML & CSS Foundations',
        order: 0,
        lessons: [
          { slug: 'html-basics', title: 'HTML Basics', type: 'explanation', estimatedMinutes: 20, order: 0 },
          { slug: 'css-basics', title: 'CSS Styling', type: 'explanation', estimatedMinutes: 25, order: 1 },
          { slug: 'responsive-design', title: 'Responsive Design', type: 'explanation', estimatedMinutes: 30, order: 2 },
        ],
      },
      {
        title: 'JavaScript Essentials',
        order: 1,
        lessons: [
          { slug: 'js-variables', title: 'Variables and Data Types', type: 'explanation', estimatedMinutes: 20, order: 0 },
          { slug: 'js-functions', title: 'Functions and Scope', type: 'explanation', estimatedMinutes: 25, order: 1 },
          { slug: 'js-dom', title: 'DOM Manipulation', type: 'explanation', estimatedMinutes: 30, order: 2 },
        ],
      },
    ],
  },
  {
    slug: 'startup-builder',
    title: 'Startup Builder',
    titleNoDiacritics: 'Startup Builder',
    description: 'From idea to MVP. Learn how to build, launch, and grow a startup using AI.',
    descriptionNoDiacritics: 'From idea to MVP. Learn how to build, launch, and grow a startup using AI.',
    icon: 'Rocket',
    color: '#10b981',
    level: 'intermediate',
    tags: ['startup', 'mvp', 'launch', 'growth'],
    totalLessons: 15,
    estimatedHours: 10,
    isPublished: true,
    modules: [
      {
        title: 'Idea Validation',
        order: 0,
        lessons: [
          { slug: 'finding-ideas', title: 'Finding Startup Ideas', type: 'explanation', estimatedMinutes: 20, order: 0 },
          { slug: 'market-research', title: 'Market Research Basics', type: 'explanation', estimatedMinutes: 25, order: 1 },
          { slug: 'mvp-planning', title: 'Planning Your MVP', type: 'explanation', estimatedMinutes: 30, order: 2 },
        ],
      },
    ],
  },
  {
    slug: 'ai-agents-advanced',
    title: 'Advanced AI Agents',
    titleNoDiacritics: 'Advanced AI Agents',
    description: 'Build autonomous AI agents that can browse, code, and execute tasks.',
    descriptionNoDiacritics: 'Build autonomous AI agents that can browse, code, and execute tasks.',
    icon: 'Bot',
    color: '#a855f7',
    level: 'advanced',
    tags: ['ai', 'agents', 'automation', 'coding'],
    totalLessons: 10,
    estimatedHours: 8,
    isPublished: true,
    modules: [
      {
        title: 'Agent Architecture',
        order: 0,
        lessons: [
          { slug: 'agent-patterns', title: 'Agent Design Patterns', type: 'explanation', estimatedMinutes: 30, order: 0 },
          { slug: 'tool-calling', title: 'Tool Calling and Function Execution', type: 'explanation', estimatedMinutes: 35, order: 1 },
        ],
      },
    ],
  },
]

export const SEED_BOOKS = [
  {
    slug: 'the-builders-handbook',
    title: "The Builder's Handbook",
    titleNoDiacritics: "The Builder's Handbook",
    description: 'A practical guide to building software products with AI.',
    descriptionNoDiacritics: 'A practical guide to building software products with AI.',
    coverColor: '#f59e0b',
    totalChapters: 8,
    isPublished: true,
    chapters: [
      { title: 'Mindset of a Builder', order: 0 },
      { title: 'Choosing Your Stack', order: 1 },
      { title: 'AI as Your Co-Pilot', order: 2 },
      { title: 'Building Your First Product', order: 3 },
      { title: 'Launching and Getting Users', order: 4 },
      { title: 'Iteration and Growth', order: 5 },
      { title: 'Scaling with AI', order: 6 },
      { title: 'The Future of Building', order: 7 },
    ],
  },
  {
    slug: 'ai-prompting-guide',
    title: 'The Art of AI Prompting',
    titleNoDiacritics: 'The Art of AI Prompting',
    description: 'Master the skill of talking to AI effectively.',
    descriptionNoDiacritics: 'Master the skill of talking to AI effectively.',
    coverColor: '#3b82f6',
    totalChapters: 6,
    isPublished: true,
    chapters: [
      { title: 'How AI Thinks', order: 0 },
      { title: 'Anatomy of a Great Prompt', order: 1 },
      { title: 'Prompt Patterns', order: 2 },
      { title: 'Debugging with AI', order: 3 },
      { title: 'Code Generation Techniques', order: 4 },
      { title: 'Advanced Strategies', order: 5 },
    ],
  },
]

export const SEED_PROMPTS = [
  {
    title: 'Create a Landing Page',
    content: 'Create a modern, responsive landing page for [PRODUCT]. Include: hero section with headline and CTA, features grid (3-4 features), testimonials section, pricing table, and footer. Use a dark theme with amber accents. Make it mobile-first.',
    category: 'web',
    tags: ['landing', 'html', 'css', 'responsive'],
  },
  {
    title: 'Build a REST API',
    content: 'Build a REST API for [RESOURCE] with the following endpoints: GET (list all, get by ID), POST (create), PUT (update), DELETE. Use Express.js with TypeScript. Include input validation, error handling, and proper status codes.',
    category: 'backend',
    tags: ['api', 'express', 'typescript', 'rest'],
  },
  {
    title: 'Explain This Code',
    content: 'Explain the following code in simple terms. Break it down line by line, explain the purpose of each function, and suggest improvements if any:\n\n[PASTE CODE HERE]',
    category: 'learning',
    tags: ['explain', 'tutorial', 'beginner'],
  },
  {
    title: 'Debug This Error',
    content: 'I got this error:\n\n[PASTE ERROR]\n\nHere is my code:\n\n[PASTE CODE]\n\nFind the bug, explain what causes it, and provide the fix.',
    category: 'debugging',
    tags: ['debug', 'fix', 'error'],
  },
  {
    title: 'Design a Database Schema',
    content: 'Design a PostgreSQL database schema for [APPLICATION]. Include: table definitions with columns and types, relationships (foreign keys), indexes for common queries, and example seed data. Follow normalization best practices.',
    category: 'database',
    tags: ['database', 'postgresql', 'schema', 'sql'],
  },
  {
    title: 'Write Unit Tests',
    content: 'Write comprehensive unit tests for the following function/module:\n\n[PASTE CODE]\n\nUse Jest. Include: happy path tests, edge cases, error cases, and mocks where needed.',
    category: 'testing',
    tags: ['test', 'jest', 'unit-test', 'quality'],
  },
  {
    title: 'Create a React Component',
    content: 'Create a reusable [COMPONENT NAME] component in React with TypeScript. Props: [LIST PROPS]. Include: proper TypeScript interfaces, responsive styling with Tailwind CSS, loading and error states, and accessibility attributes.',
    category: 'web',
    tags: ['react', 'component', 'typescript', 'tailwind'],
  },
  {
    title: 'Build a Python Script',
    content: 'Write a Python script that [DESCRIBE TASK]. Use modern Python (3.10+), include type hints, docstrings, error handling, and a CLI interface with argparse.',
    category: 'backend',
    tags: ['python', 'script', 'cli', 'automation'],
  },
  {
    title: 'SEO Optimization Plan',
    content: 'Analyze this website/app idea and create an SEO optimization plan:\n\n[DESCRIBE APP]\n\nInclude: keyword research strategy, on-page SEO checklist, meta tag recommendations, content strategy, and technical SEO requirements.',
    category: 'marketing',
    tags: ['seo', 'marketing', 'growth', 'content'],
  },
  {
    title: 'Product Launch Checklist',
    content: 'Create a comprehensive product launch checklist for [PRODUCT]. Include: pre-launch (testing, analytics, landing page), launch day (deployment, monitoring, announcements), and post-launch (feedback collection, iteration).',
    category: 'business',
    tags: ['launch', 'checklist', 'product', 'startup'],
  },
]

export const SEED_TEMPLATES = [
  {
    slug: 'nextjs-boilerplate',
    name: 'Next.js Boilerplate',
    description: 'Production-ready Next.js 14 starter with TypeScript, Tailwind, and App Router.',
    icon: 'Code2',
    color: '#f59e0b',
    techStack: ['Next.js', 'TypeScript', 'Tailwind', 'React'],
    category: 'web',
    isPublic: true,
  },
  {
    slug: 'saas-starter',
    name: 'SaaS Starter Kit',
    description: 'Complete SaaS boilerplate with auth, billing, dashboard, and settings pages.',
    icon: 'Rocket',
    color: '#3b82f6',
    techStack: ['Next.js', 'Supabase', 'Stripe', 'Prisma'],
    category: 'web',
    isPublic: true,
  },
  {
    slug: 'ai-chat-app',
    name: 'AI Chat Application',
    description: 'Streaming AI chat app with conversation history and multiple model support.',
    icon: 'Bot',
    color: '#a855f7',
    techStack: ['Next.js', 'OpenRouter', 'Vercel AI SDK'],
    category: 'ai',
    isPublic: true,
  },
  {
    slug: 'portfolio-site',
    name: 'Developer Portfolio',
    description: 'Clean, modern portfolio site with projects showcase and blog.',
    icon: 'User',
    color: '#10b981',
    techStack: ['Next.js', 'MDX', 'Tailwind'],
    category: 'web',
    isPublic: true,
  },
  {
    slug: 'api-server',
    name: 'API Server',
    description: 'REST API boilerplate with auth, validation, and documentation.',
    icon: 'Code2',
    color: '#ec4899',
    techStack: ['Express', 'TypeScript', 'PostgreSQL', 'Prisma'],
    category: 'backend',
    isPublic: true,
  },
]
